### PR TITLE
GenericWriter: do not unpremult/premult before/after colorspace change.

### LINKED ISSUE #582: Writers: wrong gamma interpretation on 8-bit image formats
[writerpremult.zip](https://github.com/NatronGitHub/Natron/files/6091894/writerpremult.zip)
### Problem

When writing frames with alpha values to a format that doesn't support alpha (eg jpeg), there seems to be an extra alpha multiplication before writing.

See attached annotated project.

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 2.3.16b2
* **OS version:**

### PR DESCRIPTION
**Pull request by devernay**
```
            // We should NEVER premult in a nonlinear colorspace if the output format doesn't support
            // alpha. https://github.com/NatronGitHub/Natron/issues/582
            // If the output format doesn't support Alpha, we just do the OCIO colorspace conversion on
            // premultiplied values.
            // It corresponds to merging over solid black.
            // Note that linear OCIO colorspaces do not need the unpremult/premult operations at all,
            // and could go in the if (isOCIOIdentity) branch above, if we were able to figure out that
            // they are linear.
            //
            // The decision to unpremult/premult before/after OCIO conversion is done this way:
            // alphaOK | userPremult | pluginExpectedPremult | doUnpremultBeforeOCIO | doPremultAfterOCIO
            //   true  |      U      |            U          |           no          |         no
            //   true  |      U      |            P          |           no          |        yes
            //   true  |      P      |            U          |          yes          |         no
            //   true  |      P      |            P          |          yes          |        yes
            //  false  |      U      |            U          |           no          |         no
            //  false  |      U      |            P          |           no          |         NO
            //  false  |      P      |            U          |          yes          |         no
            //  false  |      P      |            P          |           NO          |         NO (2)
            // Note the last line: it says that when saving to a format that doesn't handle alpha (eg jpg),
            // users prefer just considering the image as opaque and dropping alpha before color conversion.

```
fixes https://github.com/NatronGitHub/Natron/issues/582
see also https://github.com/OpenImageIO/oiio/issues/2887

### CODE REVIEW

**Comment by devernay** [comment]
closing for now.I thing we still need the supportsAlpha() method, and do the unpremult/premult bracket only if target format supports alpha

**Comment by devernay** [comment]
This changes the following tests, but the new results seem correct to me (the old ones were wrong). @rodlie please review:
```
< TestConstant : FAIL
< TestDropShadow : FAIL
< TestImageEXR : FAIL
< TestImageKRA : FAIL
< TestImageORA : FAIL
< TestImagePGM : FAIL
< TestImageSVG : FAIL
< TestRetimeTransform : FAIL
< TestTimeBlur : FAIL
< TestCMD/1 : FAIL
< TestCMD/2 : FAIL
```

**Comment by rodlie** [comment]
Will do, been a bit busy these last days, but have time after work today.

**Comment by devernay** [comment]
@rodlie do the changes seem ok?

**Comment by rodlie** [comment]
Sorry for the late reply, my Linux laptop is broken, but I can test on Windows (and do builds).

**Pull request merged**
