### PR TITLE
Add Windows build to CI action.

### PR DESCRIPTION
**Pull request by acolwell**
- Adding build steps for building the plugins on Windows
- Added steps to build self contained build artifacts that can be used for testing. These artifacts contain all of the shared libraries required by the plugins and it modifies the plugin's rpath/manifest to load these shared libraries that are inside the bundle. The intent is for these artifacts to be used by other GitHub actions (e.g. Natron CI) so that those actions do not need to worry about what libraries the plugins may depend on.

### CODE REVIEW

**Review by devernay — APPROVED** [review]
Thank you!
LGTM

**Comment by devernay** [comment]
I guess I'll have to find out how to remove the appveyor build

**Comment by acolwell** [comment]
> I guess I'll have to find out how to remove the appveyor build

I think it might just involve removing .appveyor.yml.

**Comment by acolwell** [comment]
Also if you could do a quick review of https://github.com/NatronGitHub/openfx-io/pull/35 I'd appreciate it. The Windows CI depends on it to prevent hangs on shutdown.

**Comment by acolwell** [comment]
> > I guess I'll have to find out how to remove the appveyor build
> 
> I think it might just involve removing .appveyor.yml.

I removed the appveyor.yml file, but I believe you might need to remove a Webhook from the project settings to get it to stop showing up in pull requests.

**Pull request merged**
