### PR TITLE
sync ReadFFmpeg with mov64Reader 12.2v5

### PR DESCRIPTION
**Pull request by devernay**
Related issues which may be fixed by that:
- https://github.com/NatronGitHub/Natron/issues/241 (test file is not available anymore)
- https://github.com/NatronGitHub/Natron/issues/231
- https://github.com/NatronGitHub/Natron/issues/148 (the [MXF](https://mega.nz/#!D0ojBJQA!W476CDKWyBbDgQWucTaQt0WDBr8OmvJX9tT20Wdt8oM) file in that issue is read correctly)
- https://github.com/MrKepzie/openfx-io/issues/15 ([video file](http://www.neatvideo.com/files3/testkit.zip) in that issue reads correctly)
- https://github.com/NatronGitHub/openfx-io/issues/2 (for the reading part only)

### CODE REVIEW

**Comment by devernay** [comment]
@rodlie if you have more video files that Natron was unable to read, please test with this version.

**Comment by rodlie** [comment]
Awesome, will start testing with various formats.

**Comment by devernay** [comment]
Merging, since it improves compatibility, and the unit tests show no regression

**Comment by devernay** [comment]
closes https://github.com/NatronGitHub/Natron/issues/241 (test file is not available anymore)
closes https://github.com/NatronGitHub/Natron/issues/231
closes https://github.com/NatronGitHub/Natron/issues/148 (the [MXF](https://mega.nz/#!D0ojBJQA!W476CDKWyBbDgQWucTaQt0WDBr8OmvJX9tT20Wdt8oM) file in that issue is read correctly)
closes https://github.com/MrKepzie/openfx-io/issues/15 ([video file](http://www.neatvideo.com/files3/testkit.zip) in that issue reads correctly)
closes https://github.com/NatronGitHub/openfx-io/issues/2 (for the reading part only)

**Pull request merged**
